### ISSUE TITLE
Unable to load themed .vue files

### ISSUE THREAD

**Issue by aixigo-dvoss** [LaxarJS/laxar-vue-adapter#10]
When pointing `templateSource` to a `.vue` file, _in some situations_ the `vue-loader` seems to provide a module where the whole exports are wrapped in a `default` property. This causes the `templateHtml` parameter to be not compatible with the `attachRenderFunctions` function, which expects `$options` to be on the root object.

I have not yet identified why this happens only in _some_ scenarios.

**Comment by jpommerening** [comment]
Looks like we can't rely on `.vue` modules to behave consistently, so we should probably be able to handle both kinds.

**Comment by jpommerening** [comment]
Fixed on `master` (`v2.0.1`)
